apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    version: "{{ .Values.global.istio.version }}"
  name: service-mesh
  namespace: {{.Release.Namespace}}
spec:
  namespace: {{.Release.Namespace}}
  components:
    egressGateways:
      - enabled: false
        name: istio-egressgateway
        namespace: {{.Release.Namespace}}
    ingressGateways:
      - enabled: true
        k8s:
          service:
            type: {{ .Values.global.istio.service.ingressgateway.type }}
          replicaCount: {{ .Values.global.istio.replicaCount }}
          resources:
{{- toYaml .Values.global.istio.resources.ingressgateway | nindent 12 }}
        name: istio-ingressgateway
        namespace: {{.Release.Namespace}}
    pilot:
      namespace: {{.Release.Namespace}}
      enabled: true
      k8s:
        replicaCount: {{ .Values.global.istio.replicaCount }}
        resources:
{{- toYaml .Values.global.istio.resources.pilot | nindent 12 }}
  hub: {{ .Values.global.repository }}/{{ .Values.global.repositoryNamespace }}
  meshConfig:
    defaultConfig:
      proxyMetadata:
        DNS_AGENT: ""
        ISTIO_META_DNS_CAPTURE: "true"
    enableTracing: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  profile: demo
  tag: {{ .Values.global.istio.version }}
  values:
    global:
      istioNamespace: {{.Release.Namespace}}
      proxy:
        resources:
          limits:
            cpu: "2"
            memory: 1024Mi
          requests:
            cpu: "0.1"
            memory: 128Mi